config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # TODO: After switching the site auth to Devise, enable this auth protected route
  # # Sidekiq admin interface to monitor background jobs
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  # TEMP: Delete after switching the site auth to Devise, enable this auth protected route
  # # Sidekiq admin interface to monitor background jobs
  mount Sidekiq::Web => '/sidekiq',
        constraints: lambda { |request|
                       User.where(id: request.session['user_id']).first&.role&.in? %w[publisher developer]
                     }

  # Store Redirect and support page
  get 'store/order-success', to: 'pages#post_order_success', as: :post_order_success
  get 'store', to: redirect('https://store.crimethinc.com')

  # Homepage
  root to: 'home#index'

  get 'page(/1)', to: redirect { |_, _| '/' }
  get 'page/:page', to: 'home#index'

  # To Change Everything (TCE)
  get 'tce(/:lang)',
      to:       'to_change_everything#show',
      defaults: { lang: 'english' },
      as:       :to_change_everything

  # Steal Something from Work Day (SSfWD)
  get 'steal-something-from-work-day(/:locale)',
      to:       'steal_something_from_work_day#show',
      defaults: { locale: 'english' },
      as:       :steal_something_from_work_day

  # Articles
  # Article listings by year, optional month, optional day
  get '(/:year)(/:month)(/:day)/page(/1)', to: redirect { |_, req|
    req.path.split('page').first
  }
  get '/(:year)/(:month)/(:day)/(page/:page)',
      to:          'article_archives#index',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ },
      as:          :article_archives

  # Article permalink
  # no (/:lang) since slug should encompass that
  get ':year/:month/:day/:slug(.:format)',
      to:          'articles#show',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ },
      as:          :article

  # Article edit convenience route
  get ':year/:month/:day/:slug/edit',
      controller:  'admin/articles',
      action:      'edit',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }

  # Draft Articles and Pages
  get 'drafts/articles/:draft_code',            to: 'articles#show',       as: :article_draft
  get 'drafts/pages/:draft_code',               to: 'pages#show',          as: :page_draft
  get 'drafts/episodes/:draft_code',            to: 'episodes#show',       as: :episode_draft
  get 'drafts/episodes/:draft_code/transcript', to: 'episodes#transcript', as: :episode_draft_transcript

  # Draft Articles and Pages /edit convenience routes
  get 'drafts/articles/:draft_code/edit', controller: 'admin/articles', action: 'edit'

  # Articles Atom Feed
  get 'feeds',             to: 'pages#feeds',                                  as: :feeds
  get 'feed(/:lang).json', to: 'articles#index', defaults: { format: 'json' }, as: :json_feed
  get 'feed(/:lang)',      to: 'articles#index', defaults: { format: 'atom' }, as: :feed

  # Articles - Collection Items
  get 'articles/:id_or_slug/collection_posts', to: 'collection_posts#index'

  # Categories
  get 'categories',                    to: 'categories#index', as: :categories
  get 'categories/:slug/page(/1)',     to: redirect { |path_params, _| "/categories/#{path_params[:slug]}" }
  get 'categories/:slug(/page/:page)', to: 'categories#show', as: :category
  get 'categories/:slug/feed(/:lang)', to: 'categories#feed', defaults: { format: 'atom' }, as: :category_feed

  # Tags
  get 'tags/:slug/page(/1)',     to: redirect { |path_params, _| "/tags/#{path_params[:slug]}" }
  get 'tags/:slug(/page/:page)', to: 'tags#show', as: :tag
  get 'tags/:slug/feed(/:lang)', to: 'tags#feed', defaults: { format: 'atom' }, as: :tag_feed

  # Podcast
  get 'podcast/feed(/:lang)',                               to: 'podcasts#feed',        as: :podcast_feed, defaults: { format: 'rss' }
  get 'podcasts',                                           to: 'podcasts#index',       as: :podcasts
  get 'podcasts/:slug',                                     to: 'podcasts#show',        as: :podcast
  get 'podcasts/:slug/episodes',                            to: redirect { |path_params, _| "/podcasts/#{path_params[:slug]}" }
  get 'podcasts/:slug/episodes/:episode_number',            to: 'episodes#show',       as: :episode
  get 'podcasts/:slug/episodes/:episode_number/transcript', to: 'episodes#transcript', as: :episode_transcript

  # Books
  get 'books/lit-kit',        to: 'books#lit_kit',        as: :books_lit_kit
  get 'books/into-libraries', to: 'books#into_libraries', as: :books_into_libraries
  get 'books/:slug/extras',   to: 'books#extras',         as: :books_extras
  get 'books',                to: 'books#index',          as: :books
  get 'books/:slug',          to: 'books#show',           as: :book

  ## Contradictionary definitions
  get 'books/contradictionary/definitions',               to: 'definitions#index',  as: :definitions
  get 'books/contradictionary/definitions/:letter',       to: 'definitions#letter', as: :letter
  get 'books/contradictionary/definitions/:letter/:slug', to: 'definitions#show',   as: :definition

  # Videos
  get 'videos/page(/1)', to: redirect { |_, _| '/videos' }
  get 'videos',          to: 'videos#index', as: :videos
  get 'videos/:slug',    to: 'videos#show',  as: :video

  # Tools: Posters, Stickers, Zines, Journals/Issues, Logos, Music
  get 'posters',                      to: 'posters#index',  as: :posters
  get 'posters/:slug',                to: 'posters#show',   as: :poster
  get 'stickers',                     to: 'stickers#index', as: :stickers
  get 'stickers/:slug',               to: 'stickers#show',  as: :sticker
  get 'logos',                        to: 'logos#index',    as: :logos
  get 'logos/:slug',                  to: 'logos#show',     as: :logo
  get 'zines',                        to: 'zines#index',    as: :zines
  get 'zines/:slug',                  to: 'zines#show',     as: :zine
  get 'music',                        to: 'music#index',    as: :music
  get 'journals',                     to: 'journals#index', as: :journals
  get 'journals/:slug',               to: 'journals#show',  as: :journal
  get 'journals/:slug/:issue_number', to: 'issues#show',    as: :issue
  get 'journals',                     to: 'journals#index', as: :issues

  # Tools
  get 'tools',  to: 'tools#about',  as: :tools
  get 'random', to: 'tools#random', as: :random_tool

  # Site search
  get  'search',          to: 'search#index'
  get  'search/advanced', to: 'search#advanced', as: :advanced_search
  post 'search/advanced', to: 'search#advanced_search', as: :advanced_searches

  # Support
  get  'support', to: 'support#new',    as: :support
  post 'support', to: 'support#create', as: :support_create
  get  'thanks',  to: 'support#thanks', as: :thanks

  post 'support/create_session', to: 'support#create_session', as: :support_request
  get  'support/edit/:token',    to: 'support#edit',           as: :support_edit

  post 'support/cancel/:token/:subscription_id', to: 'support#cancel_subscription', as: :support_cancel_subscription
  post 'support/update/:token/:subscription_id', to: 'support#update_subscription', as: :support_update_subscription

  post 'support/stripe_subscription_payment_succeeded_webhook', to: 'support#stripe_subscription_payment_succeeded_webhook'

  # Admin Dashboard
  get :admin, to: redirect('/admin/dashboard'), as: 'admin'
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get 'markdown',  to: 'dashboard#markdown', as: :markdown

    concern :paginatable do
      get 'page(/1)', on: :collection, to: redirect { |_, req| req.path.split('page').first }
      get '(page/:page)', action: :index, on: :collection, as: ''
    end

    resources :articles, concerns: :paginatable do
      member do
        get 'new', as: :new_collection_post
      end
      collection do
        get 'draft', as: :draft
      end
    end

    resources :books,       concerns: :paginatable
    resources :categories,  concerns: :paginatable
    resources :definitions, concerns: :paginatable
    resources :episodes,    concerns: :paginatable
    resources :issues,      concerns: :paginatable
    resources :journals,    concerns: :paginatable
    resources :links,       concerns: :paginatable
    resources :locales,     concerns: :paginatable
    resources :logos,       concerns: :paginatable
    resources :pages,       concerns: :paginatable
    resources :podcasts,    concerns: :paginatable
    resources :posters,     concerns: :paginatable
    resources :redirects,   concerns: :paginatable
    resources :stickers,    concerns: :paginatable
    resources :users,       concerns: :paginatable
    resources :videos,      concerns: :paginatable
    resources :zines,       concerns: :paginatable
  end

  # Auth + User signup
  resources :users,    only: %i[create update destroy]
  resources :sessions, only: [:create]

  get 'settings', to: 'users#edit',       as: :settings
  get 'signin',   to: 'sessions#new',     as: :signin
  get 'signout',  to: 'sessions#destroy', as: :signout

  # Misc plumbing infrastructure
  get 'manifest.json',  to: 'misc#manifest_json'
  get 'opensearch.xml', to: 'misc#opensearch_xml'

  # Pages
  get 'about',                 to: 'pages#about',   as: :about,   via: :all
  get 'contact',               to: 'pages#contact', as: :contact, via: :all
  get 'library',               to: 'pages#library', as: :library
  get 'submission-guidelines', to: 'pages#submission_guidelines'

  get 'key.pub',               to: 'pages#pgp_public_key', as: :pgp_public_key, via: :all

  get 'languages',         to: 'languages#index', as: :languages
  get 'languages/:locale', to: 'languages#show',  as: :language

  # For redirection, exempts Active Storage upload paths
  get '*path', to: 'pages#show', as: :page, via: :all, constraints: lambda { |req|

app/views/2017/shared/head/_fav_and_touch_icons.html.erb
<% if media_mode? %>
  <!-- Fav and touch icons -->
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon icon" href="/apple-touch-icon.png" sizes="180x180" type="image/png">
  <link rel="mask-icon" href="/logo.svg" sizes="any" color="#000000">

  <!-- Windows, IE and Edge -->
  <meta name="msapplication-TileImage" content="<%= asset_path "icons/icon-144x144.png" %>">
  <meta name="msapplication-TileColor" content="#000000">

  <meta name="msapplication-square70x70logo" content="<%= asset_path "icons/icon-150x150.png" %>">
  <meta name="msapplication-square150x150logo" content="<%= asset_path "icons/icon-70x70.png" %>">
  <meta name="msapplication-wide310x150logo" content="<%= asset_path "icons/icon-310x150.png" %>">
  <meta name="msapplication-square310x310logo" content="<%= asset_path "icons/icon-310x310.png" %>">

  <!-- Icons and stuff for more browsers via manifest.json -->
  <link rel="manifest" href="/manifest.json">
<% end %>

<% if lite_mode? %>
  <!-- Fav and touch icons -->
  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon icon" href="/apple-touch-icon-lite.png" sizes="180x180" type="image/png">
<% end %>

app/views/2017/shared/head/_license.html.erb
<%# This spacing is to make view source license comment very readable %>

  <!--
    ********************************************************************************************************
    I support your decision, I believe in change and hope you find just what it is that you are looking for.
    <%- #= TODO note about copyright here -%>
    ********************************************************************************************************
  -->

app/views/2017/shared/head/_link_tags.html.erb
<!-- Feeds: RSS/Atom and JSON Feed -->
<% if content_for?(:auto_discovery) %>
  <%= yield :auto_discovery %>
<% else %>
  <%= auto_discovery_link_tag(:atom, feed_url,        title: page_title) %>
  <%= auto_discovery_link_tag(nil,   json_feed_url, { title: page_title, type: "application/json" }) %>
<% end %>

<!-- Canonical URLs -->
<%#= TODO rel_canonical_link_tag @post %>
<%#= TODO shorturl_link_tag      @post %>

<!-- BIO -->
<link rel="me" href="mailto:help@crimethinc.com">
<link rel="author" href="/about" title="About <%= t(:site_name) %>">

<!-- Site search -->
<link rel="search" type="application/opensearchdescription+xml" href="https://crimethinc.com/opensearch.xml" title="<%= t(:site_name) %>">

<!-- Sitemap -->
<link rel="home" href="https://crimethinc.com">
<link rel="index" href="https://crimethinc.com/sitemap">

<!-- Browser hints -->
<link rel="dns-prefetch" href="https://assets.crimethinc.com">
<link rel="dns-prefetch" href="https://cdn.crimethinc.com">

<%= yield :head %>

app/views/2017/shared/head/_lite_mode_css.html.erb
<!-- Lite Mode Styles -->
<style>
  body {
    font-family: system, -apple-system, BlinkMacSystemFont, ‘Segoe UI’, Roboto, Oxygen, Ubuntu, Cantarell, ‘Open Sans’, ‘Helvetica Neue’, sans-serif;
  }

  .header-logo {
    display: block;
    margin-bottom: 1rem;
    font-size: 2rem;
  }

  body img {
    display: none;
  }

  body#podcast .subscribe a.u-url {
    display: block;
  }

  body#tools .tool {
    margin-top: 1rem;
    border-top: 1px solid #ddd;
    padding-top: 1rem;
  }

  body#tools .tool .tool-front > a {
    display: none;
  }

  body#tools .tool > header {
    display: none;
  }

  body#tools .row#extra {
    border-top: 1px solid #ddd;
  }

  .site-header {
    margin-bottom: 15px;
  }

  .site-header nav {
    margin-bottom: 15px;
  }

  ul.primary-navigation, ul.pagination {
    display: inline-block;
    margin: 0;
  }

  ul.primary-navigation li, ul.pagination li {
    display: inline;
  }

  ul.primary-navigation {
    padding: 0;
  }

  ul.primary-navigation li + li {
    padding-left: 15px;
  }

  ul.pagination {
    padding: 15px 0 0;
  }

  .secondary-navigation form {
    margin-bottom: 15px;
  }

  .secondary-navigation .simple-field {
    border-radius: 0;
    font-weight: normal;
    font-weight: 100;
    font-size: 1rem;
    padding: 10px;
    width: 66%;
    text-transform: uppercase;
    border: 1px solid #ddd;
  }

  input[type="text"],
  input[type="search"],
  input[type="email"] {
    border-radius: 0;
    font-weight: normal;
    font-weight: 100;
    font-size: 1rem;
    padding: 10px;
    width: 66%;
    text-transform: uppercase;
    border: 1px solid #ddd;
  }

  input[type="email"],
  #mce-MMERGE3 {
    margin-bottom: 10px;
  }

  input[type="number"],
  select {
    border-radius: 0;
    font-weight: normal;
    font-size: 1rem;
    padding: 5px;
    border: 1px solid #ddd;
  }

  .actions button,
  button[type="submit"],
  input[name="commit"] {
    font-size: .86rem;
    padding: 5px;
  }

  .h-entry {
    border-bottom: 1px solid #ddd;
  }

  .h-entry .categories ul {
    display: inline-block;
    margin-top: 0;
    list-style: none;
    padding-left: 15px;
  }

  .visually-hidden,
  .sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0, 0, 0, 0);
    border: 0;
  }

  .screen-reader-only {
    display: none;
  }

  .p-x-title {
    margin: .5em 0;
    font-size: 2em;
  }

  .p-x-subtitle {
    margin-top: 0;
    font-size: 1.25em;
  }

  img[src*="start-header"] {
    display: none;
  }
</style>

app/views/2017/shared/head/_meta_tags.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="pgpkey" type="application/pgp-keys" href="/key.pub">

<%= csrf_meta_tags %>

app/views/2017/shared/head/_public_meta_tags.html.erb
<!-- Search engines should use our meta tags for link previews -->
<meta name="robots" content="noydir">
<meta name="robots" content="noodp">

<!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#000000">
<!-- Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="black">

<!-- General meta tags -->
<meta name="robots" content="index,follow">
<meta name="application-name" content="<%= page_title %>">
<meta name="description" content="<%= meta_description(find_the_thing) %>">
<meta name="generator" content="CrimethInc. Internet Rube Goldberg Machine 3000">
<meta name="author" content="<%= author %>">

app/views/2017/shared/head/_social_media_meta_tags.html.erb
<!-- Google Site Verification for WebMaster tools -->
<!-- <meta name="google-site-verification" content="<%#= TODO google-site-verification %>" /> -->

<!-- Social media support: Twitter Cards and Facebook (Open Graph) -->
<meta name="twitter:dnt" content="on">
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@crimethinc">
<meta name="twitter:site:id" content="14884161">
<meta name="twitter:creator" content="@crimethinc">
<meta name="twitter:creator:id" content="14884161">
<meta name="twitter:url" content="<%= request.url.force_encoding('UTF-8') %>" property="og:url">
<meta name="twitter:title" content="<%= meta_title find_the_thing %>" property="og:title">
<meta name="twitter:description" content="<%= meta_description find_the_thing %>" property="og:description">
<meta name="twitter:image" content="<%= meta_image find_the_thing %>" property="og:image">
<meta property="og:site_name" content="<%= t :site_name %>">
<meta property="og:type" content="<%= meta_type find_the_thing %>">

app/views/2017/shared/head/_stylesheets.html.erb
<!-- CSS -->
<%= stylesheet_link_tag Current.theme, media: "all" unless lite_mode? %>

<style>
  <% if @article.present? && @article.css.present? %>
    <!-- Custom Article CSS -->
    <%= @article.css %>
  <% end %>

  <% if @page.present? && @page.css.present? %>
    <!-- Custom Page CSS -->
    <%= @page.css %>
  <% end %>
</style>

<%= render_themed "shared/head/lite_mode_css" if lite_mode? %>