config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # TODO: After switching the site auth to Devise, enable this auth protected route
  # # Sidekiq admin interface to monitor background jobs
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  # TEMP: Delete after switching the site auth to Devise, enable this auth protected route
  # # Sidekiq admin interface to monitor background jobs
  mount Sidekiq::Web => '/sidekiq',
        constraints: lambda { |request|
                       User.where(id: request.session['user_id']).first&.role&.in? %w[publisher developer]
                     }

  # Store Redirect and support page
  get 'store/order-success', to: 'pages#post_order_success', as: :post_order_success
  get 'store', to: redirect('https://store.crimethinc.com')

  # Homepage
  root to: 'home#index'

  get 'page(/1)', to: redirect { |_, _| '/' }
  get 'page/:page', to: 'home#index'

  # To Change Everything (TCE)
  get 'tce(/:lang)',
      to:       'to_change_everything#show',
      defaults: { lang: 'english' },
      as:       :to_change_everything

  # Steal Something from Work Day (SSfWD)
  get 'steal-something-from-work-day(/:locale)',
      to:       'steal_something_from_work_day#show',
      defaults: { locale: 'english' },
      as:       :steal_something_from_work_day

  # Articles
  # Article listings by year, optional month, optional day
  get '(/:year)(/:month)(/:day)/page(/1)', to: redirect { |_, req|
    req.path.split('page').first
  }
  get '/(:year)/(:month)/(:day)/(page/:page)',
      to:          'article_archives#index',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ },
      as:          :article_archives

  # Article permalink
  # no (/:lang) since slug should encompass that
  get ':year/:month/:day/:slug(.:format)',
      to:          'articles#show',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ },
      as:          :article

  # Article edit convenience route
  get ':year/:month/:day/:slug/edit',
      controller:  'admin/articles',
      action:      'edit',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }

  # Draft Articles and Pages
  get 'drafts/articles/:draft_code',            to: 'articles#show',       as: :article_draft
  get 'drafts/pages/:draft_code',               to: 'pages#show',          as: :page_draft
  get 'drafts/episodes/:draft_code',            to: 'episodes#show',       as: :episode_draft
  get 'drafts/episodes/:draft_code/transcript', to: 'episodes#transcript', as: :episode_draft_transcript

  # Draft Articles and Pages /edit convenience routes
  get 'drafts/articles/:draft_code/edit', controller: 'admin/articles', action: 'edit'

  # Articles Atom Feed
  get 'feeds',             to: 'pages#feeds',                                  as: :feeds
  get 'feed(/:lang).json', to: 'articles#index', defaults: { format: 'json' }, as: :json_feed
  get 'feed(/:lang)',      to: 'articles#index', defaults: { format: 'atom' }, as: :feed

  # Articles - Collection Items
  get 'articles/:id_or_slug/collection_posts', to: 'collection_posts#index'

  # Categories
  get 'categories',                    to: 'categories#index', as: :categories
  get 'categories/:slug/page(/1)',     to: redirect { |path_params, _| "/categories/#{path_params[:slug]}" }
  get 'categories/:slug(/page/:page)', to: 'categories#show', as: :category
  get 'categories/:slug/feed(/:lang)', to: 'categories#feed', defaults: { format: 'atom' }, as: :category_feed

  # Tags
  get 'tags/:slug/page(/1)',     to: redirect { |path_params, _| "/tags/#{path_params[:slug]}" }
  get 'tags/:slug(/page/:page)', to: 'tags#show', as: :tag
  get 'tags/:slug/feed(/:lang)', to: 'tags#feed', defaults: { format: 'atom' }, as: :tag_feed

  # Podcast
  get 'podcast/feed(/:lang)',                               to: 'podcasts#feed',        as: :podcast_feed, defaults: { format: 'rss' }
  get 'podcasts',                                           to: 'podcasts#index',       as: :podcasts
  get 'podcasts/:slug',                                     to: 'podcasts#show',        as: :podcast
  get 'podcasts/:slug/episodes',                            to: redirect { |path_params, _| "/podcasts/#{path_params[:slug]}" }
  get 'podcasts/:slug/episodes/:episode_number',            to: 'episodes#show',       as: :episode
  get 'podcasts/:slug/episodes/:episode_number/transcript', to: 'episodes#transcript', as: :episode_transcript

  # Books
  get 'books/lit-kit',        to: 'books#lit_kit',        as: :books_lit_kit
  get 'books/into-libraries', to: 'books#into_libraries', as: :books_into_libraries
  get 'books/:slug/extras',   to: 'books#extras',         as: :books_extras
  get 'books',                to: 'books#index',          as: :books
  get 'books/:slug',          to: 'books#show',           as: :book

  ## Contradictionary definitions
  get 'books/contradictionary/definitions',               to: 'definitions#index',  as: :definitions
  get 'books/contradictionary/definitions/:letter',       to: 'definitions#letter', as: :letter
  get 'books/contradictionary/definitions/:letter/:slug', to: 'definitions#show',   as: :definition

  # Videos
  get 'videos/page(/1)', to: redirect { |_, _| '/videos' }
  get 'videos',          to: 'videos#index', as: :videos
  get 'videos/:slug',    to: 'videos#show',  as: :video

  # Tools: Posters, Stickers, Zines, Journals/Issues, Logos, Music
  get 'posters',                      to: 'posters#index',  as: :posters
  get 'posters/:slug',                to: 'posters#show',   as: :poster
  get 'stickers',                     to: 'stickers#index', as: :stickers
  get 'stickers/:slug',               to: 'stickers#show',  as: :sticker
  get 'logos',                        to: 'logos#index',    as: :logos
  get 'logos/:slug',                  to: 'logos#show',     as: :logo
  get 'zines',                        to: 'zines#index',    as: :zines
  get 'zines/:slug',                  to: 'zines#show',     as: :zine
  get 'music',                        to: 'music#index',    as: :music
  get 'journals',                     to: 'journals#index', as: :journals
  get 'journals/:slug',               to: 'journals#show',  as: :journal
  get 'journals/:slug/:issue_number', to: 'issues#show',    as: :issue
  get 'journals',                     to: 'journals#index', as: :issues

  # Tools
  get 'tools',  to: 'tools#about',  as: :tools
  get 'random', to: 'tools#random', as: :random_tool

  # Site search
  get  'search',          to: 'search#index'
  get  'search/advanced', to: 'search#advanced', as: :advanced_search
  post 'search/advanced', to: 'search#advanced_search', as: :advanced_searches

  # Support
  get  'support', to: 'support#new',    as: :support
  post 'support', to: 'support#create', as: :support_create
  get  'thanks',  to: 'support#thanks', as: :thanks

  post 'support/create_session', to: 'support#create_session', as: :support_request
  get  'support/edit/:token',    to: 'support#edit',           as: :support_edit

  post 'support/cancel/:token/:subscription_id', to: 'support#cancel_subscription', as: :support_cancel_subscription
  post 'support/update/:token/:subscription_id', to: 'support#update_subscription', as: :support_update_subscription

  post 'support/stripe_subscription_payment_succeeded_webhook', to: 'support#stripe_subscription_payment_succeeded_webhook'

  # Admin Dashboard
  get :admin, to: redirect('/admin/dashboard'), as: 'admin'
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get 'markdown',  to: 'dashboard#markdown', as: :markdown

    concern :paginatable do
      get 'page(/1)', on: :collection, to: redirect { |_, req| req.path.split('page').first }
      get '(page/:page)', action: :index, on: :collection, as: ''
    end

    resources :articles, concerns: :paginatable do
      member do
        get 'new', as: :new_collection_post
      end
      collection do
        get 'draft', as: :draft
      end
    end

    resources :books,       concerns: :paginatable
    resources :categories,  concerns: :paginatable
    resources :definitions, concerns: :paginatable
    resources :episodes,    concerns: :paginatable
    resources :issues,      concerns: :paginatable
    resources :journals,    concerns: :paginatable
    resources :links,       concerns: :paginatable
    resources :locales,     concerns: :paginatable
    resources :logos,       concerns: :paginatable
    resources :pages,       concerns: :paginatable
    resources :podcasts,    concerns: :paginatable
    resources :posters,     concerns: :paginatable
    resources :redirects,   concerns: :paginatable
    resources :stickers,    concerns: :paginatable
    resources :users,       concerns: :paginatable
    resources :videos,      concerns: :paginatable
    resources :zines,       concerns: :paginatable
  end

  # Auth + User signup
  resources :users,    only: %i[create update destroy]
  resources :sessions, only: [:create]

  get 'settings', to: 'users#edit',       as: :settings
  get 'signin',   to: 'sessions#new',     as: :signin
  get 'signout',  to: 'sessions#destroy', as: :signout

  # Misc plumbing infrastructure
  get 'manifest.json',  to: 'misc#manifest_json'
  get 'opensearch.xml', to: 'misc#opensearch_xml'

  # Pages
  get 'about',                 to: 'pages#about',   as: :about,   via: :all
  get 'contact',               to: 'pages#contact', as: :contact, via: :all
  get 'library',               to: 'pages#library', as: :library
  get 'submission-guidelines', to: 'pages#submission_guidelines'

  get 'key.pub',               to: 'pages#pgp_public_key', as: :pgp_public_key, via: :all

  get 'languages',         to: 'languages#index', as: :languages
  get 'languages/:locale', to: 'languages#show',  as: :language

  # For redirection, exempts Active Storage upload paths
  get '*path', to: 'pages#show', as: :page, via: :all, constraints: lambda { |req|

app/views/admin/_danger_zone.html.erb
<div class="card text-white bg-danger mb-5" style="margin-top: 10rem">
  <div class="card-header h3">The Danger Zone™</div>

  <div class="card-body bg-light text-dark">
    <h2 class="card-title text-danger h5">
      Want to delete this <%= label.humanize.titleize %>?
    </h2>

    <p class="card-text">
      You can delete this <%= label.humanize.titleize %> at anytime.
      All of its associated data will be immediately and permanently deleted.
      There is <b>NO UNDO</b>.
    </p>

    <div class="text-right">
      <%= link_to "Delete", path, method: :delete, data: { confirm: "Are you sure you’re sure? There is NO UNDO." }, class: "btn btn-danger btn-sm" %>
    </div>
  </div>
</div>

app/views/admin/_datetime_group.html.erb
<div class="mb-3" id="publication_datetime">
  <%= form.label :published_at, "Publication Date &amp; Time".html_safe, class: "form-label" %>

  <div class="row">
    <div class="col-12">
      <input id="publication_date"
             placeholder="YYYY-MM-DD"
             type="date"
             name="published_at_date"
             value="<%= admin_form_date(post) %>"
             class="form-select form-select-lg"
             autocomplete="off">

      <p class="form-text text-muted">Example: 1999-11-30</p>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <input id="publication_time"
             placeholder="HH:MM"
             type="time"
             name="published_at_time"
             value="<%= admin_form_time(post) %>"
             class="form-select form-select-lg"
             autocomplete="off">

      <p class="form-text text-muted">Example: 23:59</p>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= time_zone_select type,
                           :published_at_tz,
                           [ActiveSupport::TimeZone['Pacific Time (US & Canada)'], ActiveSupport::TimeZone['Eastern Time (US & Canada)']],
                           {},
                           class: "form-select form-select-lg mb-2" %>
    </div>
  </div>
</div>

app/views/admin/_form_actions.html.erb
<%# TODO there's got to be a better way! %>
<% button_text ||= "Save" %>

<div class="actions">
  <%= link_to "Cancel", cancel_url, class: "cancel action-cancel" %>
  <%= button_tag button_text, class: "btn btn-primary btn-lg" %>
</div>

app/views/admin/_form_errors.html.erb
<% if thing.errors.any? %>
  <% thing.errors.full_messages.uniq.each do |message| %>
    <div class="alert alert-danger" role="alert">
      <%= message %>.
    </div>
  <% end %>
<% end %>

app/views/admin/_label_and_area_form_group.html.erb
<% label_text ||= nil %>
<% rows       ||= nil %>

<div class="mb-3">
  <%= form.label     attr, label_text, class: "form-label" %>
  <%= form.text_area attr, class: "form-control form-control-lg", rows: rows %>
</div>

app/views/admin/_label_and_field_form_group.html.erb
<% label_text ||= nil %>
<% autofocus  ||= false %>

<div class="mb-3">
  <%= form.label      attr, label_text, class: "form-label" %>
  <%= form.text_field attr, class: "form-control form-control-lg", autofocus: autofocus %>
</div>

app/views/admin/_nav.html.erb
<% if signed_in? %>
  <nav class="navbar navbar-expand-md navbar-light bg-light border border-secondary border-top-0 border-start-0 border-end-0 mb-5">
    <div class="container-fluid">
      <%= link_to "🖤 ADMIN", [:admin, :dashboard], class: "navbar-brand" %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto me-auto mb-2 mb-lg-0">
          <%= nav_to "📝 New Article",  [:new, :admin, :article] %>
          <%= nav_to "📄 Articles",     [:admin, :articles] %>
          <%= nav_to "↪️ Redirects",    [:admin, :redirects] %>
          <%= nav_to "⤴️ New Redirect", [:new, :admin, :redirect] %>
        </ul>

        <div class="d-flex">
          <ul class="navbar-nav">
            <%= nav_to "🖥 View Site", [:root], target: "_blank" %>
          </ul>
        </div>
      </div>
    </div>
  </nav>
<% end %>

app/views/admin/_page_header.html.erb
<div class="mb-5">
  <h1>
    <%= link_to_unless_current current_resource_name.pluralize, [:admin, current_resource_name.tableize.to_sym] %>
  </h1>

  <p>
    <% if action_name == 'index' %>
      <%= link_to "NEW", [:new, :admin, current_resource_name.downcase.to_sym], class: "btn btn-outline-primary btn-sm action-new" %>
    <% elsif action_name == 'show' %>
      <%= link_to "EDIT", [:edit, :admin, thing], class: "btn btn-light border-secondary btn-sm action-edit" %>
    <% end %>
  </p>

  <% if action_name == 'edit' %>
    <h2>Editing <%= link_to thing.name, [:admin, thing] %></h2>
  <% end %>

  <% if action_name == 'new' %>
    <h2>New <%= current_resource_name %></h2>
  <% end %>
</div>

app/views/admin/_publication_status.html.erb
<div class="card mb-3 bg-light">
  <div class="card-body">
    <div id="publication-status">
      <%= form.label :publication_status, "Publication Status", class: "form-label" %><br>

      <% Publishable.publication_statuses_for(user: Current.user).each do |state| %>
        <%= form.radio_button :publication_status, state, id: "publication_status_#{state}", class: "btn-check" %>

        <%= form.label "publication_status_#{state}",
                       state.capitalize,
                       for: "publication_status_#{state}",
                       class: "btn btn-outline-#{state == :draft ? :secondary : 'primary'}" %>
      <% end %>
    </div><!-- #publication-status -->
  </div>
</div>

app/views/admin/_translate_this.html.erb
<div class="translate-this">
  <p class="p-0 m-0">Translate this to</p>

  <% Locale.all.each do |locale| %>
    <% next if locale.english? %>
    <% next if resource.localizations.map(&:locale).include? locale.abbreviation %>

    <%= link_to locale.abbreviation.upcase,
                [:new, :admin, resource.class.to_s.downcase.to_sym, canonical_id: resource.id, locale: locale.abbreviation],
                class: "btn btn-outline-primary btn-sm mb-2" %>
  <% end %>
</div>