config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # TODO: After switching the site auth to Devise, enable this auth protected route
  # # Sidekiq admin interface to monitor background jobs
  # authenticate :user, ->(user) { user.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  # TEMP: Delete after switching the site auth to Devise, enable this auth protected route
  # # Sidekiq admin interface to monitor background jobs
  mount Sidekiq::Web => '/sidekiq',
        constraints: lambda { |request|
                       User.where(id: request.session['user_id']).first&.role&.in? %w[publisher developer]
                     }

  # Store Redirect and support page
  get 'store/order-success', to: 'pages#post_order_success', as: :post_order_success
  get 'store', to: redirect('https://store.crimethinc.com')

  # Homepage
  root to: 'home#index'

  get 'page(/1)', to: redirect { |_, _| '/' }
  get 'page/:page', to: 'home#index'

  # To Change Everything (TCE)
  get 'tce(/:lang)',
      to:       'to_change_everything#show',
      defaults: { lang: 'english' },
      as:       :to_change_everything

  # Steal Something from Work Day (SSfWD)
  get 'steal-something-from-work-day(/:locale)',
      to:       'steal_something_from_work_day#show',
      defaults: { locale: 'english' },
      as:       :steal_something_from_work_day

  # Articles
  # Article listings by year, optional month, optional day
  get '(/:year)(/:month)(/:day)/page(/1)', to: redirect { |_, req|
    req.path.split('page').first
  }
  get '/(:year)/(:month)/(:day)/(page/:page)',
      to:          'article_archives#index',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ },
      as:          :article_archives

  # Article permalink
  # no (/:lang) since slug should encompass that
  get ':year/:month/:day/:slug(.:format)',
      to:          'articles#show',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ },
      as:          :article

  # Article edit convenience route
  get ':year/:month/:day/:slug/edit',
      controller:  'admin/articles',
      action:      'edit',
      constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }

  # Draft Articles and Pages
  get 'drafts/articles/:draft_code',            to: 'articles#show',       as: :article_draft
  get 'drafts/pages/:draft_code',               to: 'pages#show',          as: :page_draft
  get 'drafts/episodes/:draft_code',            to: 'episodes#show',       as: :episode_draft
  get 'drafts/episodes/:draft_code/transcript', to: 'episodes#transcript', as: :episode_draft_transcript

  # Draft Articles and Pages /edit convenience routes
  get 'drafts/articles/:draft_code/edit', controller: 'admin/articles', action: 'edit'

  # Articles Atom Feed
  get 'feeds',             to: 'pages#feeds',                                  as: :feeds
  get 'feed(/:lang).json', to: 'articles#index', defaults: { format: 'json' }, as: :json_feed
  get 'feed(/:lang)',      to: 'articles#index', defaults: { format: 'atom' }, as: :feed

  # Articles - Collection Items
  get 'articles/:id_or_slug/collection_posts', to: 'collection_posts#index'

  # Categories
  get 'categories',                    to: 'categories#index', as: :categories
  get 'categories/:slug/page(/1)',     to: redirect { |path_params, _| "/categories/#{path_params[:slug]}" }
  get 'categories/:slug(/page/:page)', to: 'categories#show', as: :category
  get 'categories/:slug/feed(/:lang)', to: 'categories#feed', defaults: { format: 'atom' }, as: :category_feed

  # Tags
  get 'tags/:slug/page(/1)',     to: redirect { |path_params, _| "/tags/#{path_params[:slug]}" }
  get 'tags/:slug(/page/:page)', to: 'tags#show', as: :tag
  get 'tags/:slug/feed(/:lang)', to: 'tags#feed', defaults: { format: 'atom' }, as: :tag_feed

  # Podcast
  get 'podcast/feed(/:lang)',                               to: 'podcasts#feed',        as: :podcast_feed, defaults: { format: 'rss' }
  get 'podcasts',                                           to: 'podcasts#index',       as: :podcasts
  get 'podcasts/:slug',                                     to: 'podcasts#show',        as: :podcast
  get 'podcasts/:slug/episodes',                            to: redirect { |path_params, _| "/podcasts/#{path_params[:slug]}" }
  get 'podcasts/:slug/episodes/:episode_number',            to: 'episodes#show',       as: :episode
  get 'podcasts/:slug/episodes/:episode_number/transcript', to: 'episodes#transcript', as: :episode_transcript

  # Books
  get 'books/lit-kit',        to: 'books#lit_kit',        as: :books_lit_kit
  get 'books/into-libraries', to: 'books#into_libraries', as: :books_into_libraries
  get 'books/:slug/extras',   to: 'books#extras',         as: :books_extras
  get 'books',                to: 'books#index',          as: :books
  get 'books/:slug',          to: 'books#show',           as: :book

  ## Contradictionary definitions
  get 'books/contradictionary/definitions',               to: 'definitions#index',  as: :definitions
  get 'books/contradictionary/definitions/:letter',       to: 'definitions#letter', as: :letter
  get 'books/contradictionary/definitions/:letter/:slug', to: 'definitions#show',   as: :definition

  # Videos
  get 'videos/page(/1)', to: redirect { |_, _| '/videos' }
  get 'videos',          to: 'videos#index', as: :videos
  get 'videos/:slug',    to: 'videos#show',  as: :video

  # Tools: Posters, Stickers, Zines, Journals/Issues, Logos, Music
  get 'posters',                      to: 'posters#index',  as: :posters
  get 'posters/:slug',                to: 'posters#show',   as: :poster
  get 'stickers',                     to: 'stickers#index', as: :stickers
  get 'stickers/:slug',               to: 'stickers#show',  as: :sticker
  get 'logos',                        to: 'logos#index',    as: :logos
  get 'logos/:slug',                  to: 'logos#show',     as: :logo
  get 'zines',                        to: 'zines#index',    as: :zines
  get 'zines/:slug',                  to: 'zines#show',     as: :zine
  get 'music',                        to: 'music#index',    as: :music
  get 'journals',                     to: 'journals#index', as: :journals
  get 'journals/:slug',               to: 'journals#show',  as: :journal
  get 'journals/:slug/:issue_number', to: 'issues#show',    as: :issue
  get 'journals',                     to: 'journals#index', as: :issues

  # Tools
  get 'tools',  to: 'tools#about',  as: :tools
  get 'random', to: 'tools#random', as: :random_tool

  # Site search
  get  'search',          to: 'search#index'
  get  'search/advanced', to: 'search#advanced', as: :advanced_search
  post 'search/advanced', to: 'search#advanced_search', as: :advanced_searches

  # Support
  get  'support', to: 'support#new',    as: :support
  post 'support', to: 'support#create', as: :support_create
  get  'thanks',  to: 'support#thanks', as: :thanks

  post 'support/create_session', to: 'support#create_session', as: :support_request
  get  'support/edit/:token',    to: 'support#edit',           as: :support_edit

  post 'support/cancel/:token/:subscription_id', to: 'support#cancel_subscription', as: :support_cancel_subscription
  post 'support/update/:token/:subscription_id', to: 'support#update_subscription', as: :support_update_subscription

  post 'support/stripe_subscription_payment_succeeded_webhook', to: 'support#stripe_subscription_payment_succeeded_webhook'

  # Admin Dashboard
  get :admin, to: redirect('/admin/dashboard'), as: 'admin'
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    get 'markdown',  to: 'dashboard#markdown', as: :markdown

    concern :paginatable do
      get 'page(/1)', on: :collection, to: redirect { |_, req| req.path.split('page').first }
      get '(page/:page)', action: :index, on: :collection, as: ''
    end

    resources :articles, concerns: :paginatable do
      member do
        get 'new', as: :new_collection_post
      end
      collection do
        get 'draft', as: :draft
      end
    end

    resources :books,       concerns: :paginatable
    resources :categories,  concerns: :paginatable
    resources :definitions, concerns: :paginatable
    resources :episodes,    concerns: :paginatable
    resources :issues,      concerns: :paginatable
    resources :journals,    concerns: :paginatable
    resources :links,       concerns: :paginatable
    resources :locales,     concerns: :paginatable
    resources :logos,       concerns: :paginatable
    resources :pages,       concerns: :paginatable
    resources :podcasts,    concerns: :paginatable
    resources :posters,     concerns: :paginatable
    resources :redirects,   concerns: :paginatable
    resources :stickers,    concerns: :paginatable
    resources :users,       concerns: :paginatable
    resources :videos,      concerns: :paginatable
    resources :zines,       concerns: :paginatable
  end

  # Auth + User signup
  resources :users,    only: %i[create update destroy]
  resources :sessions, only: [:create]

  get 'settings', to: 'users#edit',       as: :settings
  get 'signin',   to: 'sessions#new',     as: :signin
  get 'signout',  to: 'sessions#destroy', as: :signout

  # Misc plumbing infrastructure
  get 'manifest.json',  to: 'misc#manifest_json'
  get 'opensearch.xml', to: 'misc#opensearch_xml'

  # Pages
  get 'about',                 to: 'pages#about',   as: :about,   via: :all
  get 'contact',               to: 'pages#contact', as: :contact, via: :all
  get 'library',               to: 'pages#library', as: :library
  get 'submission-guidelines', to: 'pages#submission_guidelines'

  get 'key.pub',               to: 'pages#pgp_public_key', as: :pgp_public_key, via: :all

  get 'languages',         to: 'languages#index', as: :languages
  get 'languages/:locale', to: 'languages#show',  as: :language

  # For redirection, exempts Active Storage upload paths
  get '*path', to: 'pages#show', as: :page, via: :all, constraints: lambda { |req|

app/views/2020/shared/_admin_header.html.erb
<% if signed_in? %>
  <div class="bg-danger p-3">
    <div class="container">
      <div class="row">

        <div class="col-12 col-lg-6">
          <%= link_to "🖤 ADMIN Dashboard",    admin_path, class: "btn btn-light mr-2 mb-2" %>
          <%= link_to "↓ Scroll to Site Top", "#header",  class: "btn btn-light mr-2 mb-2" %>

          <% if @editable.present? %>
            <%= link_to "📝 Edit #{@editable.class}", [:edit, :admin, @editable], class: "btn btn-light mr-2 mb-2" %>
          <% end %>
        </div>

        <div class="col-12 col-lg-6">
          <% if @editable.present? %>
            <p class="mb-0 text-white d-lg-inline font-weight-bold mr-1">Translate <%= @editable.class %> to</p>

            <% Locale.all.each do |locale| %>
              <% next if locale.english? %>
              <% next if @editable.localizations.map(&:locale).include? locale.abbreviation %>

              <%= link_to locale.abbreviation.upcase,
                          [:new, :admin, @editable.class.to_s.downcase, canonical_id: @editable.id, locale: locale.abbreviation],
                          class: "btn btn-secondary btn-sm mb-2" %>
            <% end %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/2020/shared/_development_mode_banner.html.erb
<% if Rails.env.development? %>
  <div class="h1 font-weight-light text-center p-4 bg-warning">
    DEVELOPMENT MODE
  </div>
<% end %>

app/views/2020/shared/_footer.html.erb
<footer id='site-footer' class='container mt-5' role='contentinfo'>
  <div class='row'>
    <div class='col-12 col-md-6 pr-5 mb-5'>
      <nav>
        <h2><%= t 'footer.nav.heading' %></h2>

        <dl>
          <dt class='nav-label nav-label-articles'>
            <%= link_to t('footer.nav.articles.label'),   %i[library] %>
            <small class='text-muted font-weight-normal'><%= link_to t('footer.nav.articles.feed'), %i[feed] %></small>
          </dt>
          <dd>
            <% %w[arts adventure analysis current_events history how_to news technology].each do |category| %>
              <%= link_to t("footer.nav.articles.#{category}"), [:category, slug: category.dasherize] %>
            <% end %>
          </dd>

          <dt class='nav-label nav-label-articles'>
            <%= link_to t('footer.nav.tools.label'), %i[tools] %>
          </dt>
          <dd>
            <% %w[zines journals posters stickers videos music logos to_change_everything steal_something_from_work_day].each do |tool| %>
              <%= link_to t("footer.nav.tools.#{tool.to_sym}"), [tool.to_sym] %>
            <% end %>
          </dd>

          <dt class='nav-label nav-label-books'><%= link_to t('footer.nav.books.label'), %i[books] %></dt>
          <dd>
            <% %w[from_democracy_to_freedom contradictionary work expect_resistance recipes_for_disaster days_of_war_nights_of_love no_wall_they_can_build off_the_map].each do |book| %>
              <%= link_to t("footer.nav.books.#{book}"), [:book, slug: book.dasherize] %>
            <% end %>
          </dd>

          <dt class='nav-label nav-label-podcast'>
            <%= link_to t('footer.nav.podcast.label'),   %i[podcasts] %>
            <small class='text-muted font-weight-normal'><%= link_to t('footer.nav.podcast.feed'), %i[podcast_feed] %></small>
          </dt>
          <dd>
            <% %w[the_ex_worker no_wall_they_can_build the_hotwire].each do |podcast| %>
              <%= link_to t("footer.nav.podcast.#{podcast}"), "/podcasts/#{podcast.dasherize}" %>
            <% end %>
          </dd>

          <dt class='nav-label nav-label-store'><%= link_to t('footer.nav.store.label'), '/store' %></dt>
          <dd>
            <%= link_to t('footer.nav.store.description'), '/store' %>
          </dd>

          <dt class='nav-label nav-label-languages' id='languages'><%= link_to t('header.languages'), [:languages] %></dt>
          <dd>
            <% Locale.live.each do |locale| %>
              <%= link_to locale.name, [:language, locale: locale.name.downcase.gsub(' ', '-')] %>
            <% end %>
          </dd>
        </dl>

        <% if media_mode? && I18n.locale == :en %>
          <p>
            <%= link_to(t('footer.site_mode'), url_for_current_path_with_subdomain(subdomain: :lite)) %>
          </p>
        <% end %>

      </nav>
    </div><!-- .col-12 col-md-6 -->

    <div class='col-12 col-md-3 mb-5'>
      <h2><%= t('footer.contact.social.heading') %></h2>
      <%= render_markdown t('footer.contact.social.description') %>

      <ul class='list-unstyled'>
        <% social_links_by_domain.each do |domain, url| %>
          <li class='mb-2'>
            <%= link_to url, class: 'my-2', target: '_blank', rel: 'noopener' do %>
              <%= image_tag "social-icons/#{domain.parameterize}.svg", size: '40x40', class: 'mr-2' %>
              <%= domain %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div><!-- .col-12 col-md-3 -->

    <div class='col-12 col-md-3 mb-5'>
      <div id='mc_embed_signup'><!-- Begin MailChimp Signup Form -->
        <h2 class='newsletter-signup-label'><%= t('footer.contact.newsletter.heading') %></h2>
        <div class='newsletter-signup-description'><%= render_markdown t('footer.contact.newsletter.description') %></div>

        <%= form_with url: '//crimethinc.us2.list-manage.com/subscribe/post?u=cb48383602b7373f496e9ba33&amp;id=344714b249', id: 'mc-embedded-subscribe-form', class: 'newsletter-signup-form validate', name: 'mc-embedded-subscribe-form', target: '_blank', rel: 'noopener', novalidate: true do |form| %>
          <div class='mc-field-group'>
            <%= form.label       'mce-EMAIL',                                         t('footer.contact.newsletter.signup_form_placeholder'), class: 'visually-hidden' %>
            <%= form.email_field :email, name: 'EMAIL', id: 'mce-EMAIL', placeholder: t('footer.contact.newsletter.signup_form_placeholder'), class: 'form-control mb-3' %>
          </div>

          <div class='mc-field-group'>
            <%= form.label 'mce-MMERGE3', t('footer.contact.newsletter.signup_form_select_placeholder'), class: 'visually-hidden' %>

            <select name='MMERGE3' class='required form-select' id='mce-MMERGE3'>
              <option value='<%= t('footer.contact.newsletter.signup_form_select_option_lot') %>'><%= t('footer.contact.newsletter.signup_form_select_option_lot') %></option>
              <option value='<%= t('footer.contact.newsletter.signup_form_select_option_little') %>'><%= t('footer.contact.newsletter.signup_form_select_option_little') %></option>
            </select>
          </div>

          <div id='mce-responses' class='clear visually-hidden'>
            <div class='response' id='mce-error-response'>  </div>
            <div class='response' id='mce-success-response'></div>
          </div>

          <div class='text-right mt-3'>
            <%= button_tag t('footer.contact.newsletter.signup_button_text'), name: 'subscribe', id: 'mc-embedded-subscribe', class: 'btn btn-outline-success btn-lg' %>
          </div>

          <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
          <% left_or_right = html_dir == 'ltr' ? 'position: absolute; left: -5000px;' : 'position: absolute; right: -5000px;' %>
          <div id='a-thing-with-an-id' style='<%= left_or_right %>' aria-hidden='true'><input type='text' name='b_cb48383602b7373f496e9ba33_344714b249' tabindex='-1' value='' autocomplete="off"></div>
        <% end %>
      </div><!--End mc_embed_signup-->
    </div><!-- .col-12 col-md-3 -->
  </div><!-- .row -->

  <div rel='license' class='text-secondary text-center my-5 py-5'>
    <p><%= t('footer.mantra').sample %></p>
  </div>
</footer>

app/views/2020/shared/_header.html.erb
<header id="header" class="container">
  <nav>
    <ul>
      <li><%= link_to tt('site_name'),       [:root] %></li>
      <li><%= link_to tt('header.books'),    [:books] %></li>
      <li><%= link_to tt('header.library'),  [:library] %></li>
      <li><%= link_to tt('header.tools'),    [:tools] %></li>
      <li><%= link_to tt('header.podcasts'), [:podcasts] %></li>
      <li><%= link_to tt('header.store'),    [:store] %></li>
      <li><%= link_to tt('header.about'),    anchor: 'about' %></li>
    </ul>

    <%= link_to tt('header.support'), [:support] %>

    <ul>
      <li><%= link_to tt('header.languages'), anchor: 'languages' %></li>
      <li><%= link_to tt('header.search'),    anchor: 'search' %></li>
      <li><%= link_to tt('header.share'),     anchor: 'share' %></li>
    </ul>
  </nav>

  <div id='languages' style='display: none;'>
    <ol>
      <% Locale.live.each do |locale| %>
        <%= tag.li class: locale_nav_item_classes_for(locale) do %>
          <%= link_to locale.name,
                      url_for_current_path_with_subdomain(subdomain: locale.abbreviation) %>
        <% end %>
      <% end %>
    </ol>
  </div>
</header>

<div id='about' style='display: none;'>
  <p><%= tt('site_name') %></p>

  <%= tt 'header.cards.about.first_time_description' %>
  <%= link_to tt('header.cards.about.first_time_link'), '/start' %>

  <%= render_markdown tt 'header.cards.about.search_description' %>

  <%= render_themed 'shared/site_search' %>

  <%= render_markdown tt 'header.cards.about.description' %>
  <p><%= tt 'header.cards.about.more_link' %></p>
</div>

<div id='search' style='display: none;'>
  <%= tt 'header.cards.search.description' %>

  <%= render_themed 'shared/site_search' %>

  <h2><%= tt 'header.cards.search.category_heading' %></h2>

  <p>
    <% Category.all.each do |category| %>
      <%= link_to category.name, [:category, slug: category.slug] %>
    <% end %>
  </p>

  <h2><%= tt 'header.cards.search.chronological_heading' %></h2>

  <p>
    <% (1996..Time.current.year).to_a.reverse_each do |year| %>
      <%= link_to year, [:article_archives, year: year] %>
    <% end %>
  </p>
</div>

<div id='share' style='display: none;'>
  <%= render_markdown tt 'header.cards.share.description' %>

  <h2><%= @page_share.title %></h2>
  <h3><%= @page_share.subtitle %></h3>

  <ul>
    <li><%= link_to tt('header.cards.share.twitter'),  @page_share.share_url_for(:twitter),  target: '_blank' %></li>
    <li><%= link_to tt('header.cards.share.facebook'), @page_share.share_url_for(:facebook), target: '_blank' %></li>
    <li><%= link_to tt('header.cards.share.tumblr'),   @page_share.share_url_for(:tumblr),   target: '_blank' %></li>
    <li><%= link_to tt('header.cards.share.email'),    @page_share.share_url_for(:email),    target: '_blank' %></li>
  </ul>
</div>

app/views/2020/shared/_site_search.html.erb
<%= form_with url: :search, role: 'search', method: 'get', local: true do %>
  <%= label_tag        :q, tt('search.form_placeholder'), class: 'screen-reader-only' %>
  <%= search_field_tag :q, @search&.query, placeholder: tt('search.form_placeholder'), id: :q, autocomplete: :off %>

  <% if @search %>
    <%= link_to tt('search.advanced.heading'), advanced_search_path(q: @search.query) %>
  <% end %>
<% end %>

app/views/2020/shared/_translation_missing_css.html.erb
<% if Rails.env.development? %>
  <style>.translation_missing { outline: 5px solid #ff0080; }</style>
<% end %>